<div class="push-1 span-22 last" style="margin-top: 15px;">
    <a href="http://rickrolled.fr/"><img src="<?php echo base_url('img/FF5400-0.png'); ?>" height="10" width="800"></a>
<h2>Mentions légales</h2><h4>&Eacute;diteur / h&eacute;bergeur / webmaster</h4>
<p>Conform&eacute;ment aux dispositions de l&rsquo;article 6-III-1 de la Loi n&deg;2004-575 du 21 juin 2004 pour la Confiance dans l&rsquo;&Eacute;conomie Num&eacute;rique, nous vous informons que :</p>
<p>Le&nbsp;site www.pole-de-competences-verre.fr est edit&eacute; par le Cerfav pour le Pôle de Compétences Verre</p>
<p>Equipe de r&eacute;daction et webmaster : L'&eacute;quipe communication du Cerfav - <a href="mailto:webmaster@cerfav.fr">webmaster@cerfav.fr</a></p>
<p>Il est h&eacute;berg&eacute; sur un serveur appartenant au Cerfav install&eacute; au <a href="http://www.ciril.fr" target="_blank">CIRIL (Centre Interuniversitaire des Ressources Informatiques de Lorraine)<br /></a>Equipe R&eacute;seau Lothaire<br />Universit&eacute; de Lorraine<br />Site du Montet<br />2, rue du Doyen Roubault<br />54500 Vandoeuvre les Nancy<br />T&eacute;l : 03 83 68 24 00<br /><a href="mailto:reseau@ciril.fr">reseau@ciril.fr</a></p>
<p>Le site www.pole-de-competences-verre.fr a &eacute;t&eacute; r&eacute;alis&eacute; int&eacute;gralement par le Cerfav en 2014, &nbsp;avec les frameworks open-source&nbsp;<a href="http://ellislab.com/codeigniter" target="_blank">CodeIgniter</a> et <a href="http://www.blueprintcss.org/" target="_blank">Blueprint CSS</a>.<br />Pour toute information compl&eacute;mentaire, vous pouvez contacter le <a title="Franck Singler webmaster Cerfav" href="mailto:webmaster@cerfav.fr" target="_blank">webmaster</a>.</p>
<h4>D&eacute;claration CNIL</h4>
<p>A partir du 9 mai 2006, les sites internet institutionnels et les fichiers de contacts &agrave; des fins d&rsquo;information et de communication externe sont dispens&eacute;s de d&eacute;claration CNIL.</p>
<p>Les traitements de donn&eacute;es personnelles ou nominatives collect&eacute;es sur ce site par le biais de formulaires en ligne ou de prises de contact par messagerie &eacute;lectronique font l&rsquo;objet d&rsquo;une d&eacute;rogation d&eacute;finie dans la <a href="http://www.cnil.fr/en-savoir-plus/deliberations/deliberation/delib/107/" target="_blank">"D&eacute;lib&eacute;ration n&deg;2006-138 du 09/05/2006 d&eacute;cidant de la dispense de d&eacute;claration des traitements constitu&eacute;s &agrave; des fins d&rsquo;information ou de communication externe"</a></p>
<p>Publication au <a href="http://www.legifrance.gouv.fr/jopdf/common/jo_pdf.jsp?numJO=0&amp;dateJO=20060603&amp;numTexte=80&amp;pageDebut=&amp;pageFin=" target="_blank">Journal Officiel de cette dispense</a>.</p>
<p>Le site "www.pole-de-competences-verre.fr" ne dispose donc pas de num&eacute;ro de d&eacute;claration CNIL.</p>
<h4>Conditions d'utilisation</h4>
<ul>
<li>L'utilisateur reconna&icirc;t avoir pris connaissance des pr&eacute;sentes conditions d'utilisation et s'engage &agrave; les respecter,</li>
<li>L'utilisateur du site internet "www.pole-de-competences-verre.fr" reconna&icirc;t disposer de la comp&eacute;tence et des moyens n&eacute;cessaires pour acc&eacute;der et utiliser ce site,</li>
<li>L'utilisateur du site internet "www.pole-de-competences-verre.fr" reconna&icirc;t avoir v&eacute;rifi&eacute; que la configuration informatique utilis&eacute;e ne contient aucun virus ou tout autre "logiciel malintentionn&eacute;" et qu'elle est en parfait &eacute;tat de fonctionnement,</li>
<li>L'&eacute;quipe r&eacute;seau Lothaire met tout en &oelig;uvre pour offrir aux utilisateurs des informations et des outils disponibles et v&eacute;rifi&eacute;s mais ne saurait &ecirc;tre tenue pour responsable des erreurs, d'une absence de disponibilit&eacute; des fonctionnalit&eacute;s et de la pr&eacute;sence de virus ou de "logiciels malintentionn&eacute;s" sur son site,</li>
<li>L'utilisateur reconna&icirc;t avoir &eacute;t&eacute; inform&eacute; que le site internet "www.pole-de-competences-verre.fr" est accessible 24 heures sur 24 et 7 jours sur 7, &agrave; l'exception des cas de force de majeure, difficult&eacute;s informatiques, difficult&eacute;s li&eacute;es &agrave; la structure des r&eacute;seaux de t&eacute;l&eacute;communication ou difficult&eacute;s d'ordre technique,</li>
<li>Les informations fournies par L'&eacute;quipe r&eacute;seau Lothaire le sont &agrave; titre indicatif et ne sauraient dispenser l'utilisateur d'une analyse compl&eacute;mentaire et personnalis&eacute;e,</li>
<li>L'&eacute;quipe r&eacute;seau Lothaire ne saurait garantir l'exactitude, la compl&eacute;tude, l'actualit&eacute; des informations diffus&eacute;es sur son site.</li>
</ul>
<p>En cons&eacute;quence, l'utilisateur reconna&icirc;t utiliser ces informations sous sa responsabilit&eacute; exclusive.</p>
<h4>Cookies</h4>
<p>Une description des cookies informatiques est disponible en suivant le lien : <a href="http://fr.wikipedia.org/wiki/Cookie_(informatique)">http://fr.wikipedia.org/wiki/Cookie_(informatique)</a></p>
<p>La partie "publique" du site "www.pole-de-competences-verre.fr" n'a pas besoin de cookies pour fonctionner, mais en utilise uniquement &agrave; des fins de statistiques de consultation. La partie "priv&eacute;e" utilise les cookies pour le maintien de la connexion.<br />L'utilisateur qui n'acc&egrave;de qu'&agrave; la partie "publique" du site peut donc d&eacute;sactiver les cookies dans son navigateur sans incidence sur les fonctionnalit&eacute;s de ce site.<br />N&eacute;anmoins, l'utilisation des cookies permet de proposer des fonctionnalit&eacute;s plus riches et si l'utilisateur les autorise, il est inform&eacute; de ce qui suit.<br />L'utilisateur est inform&eacute; que lors de ses visites sur le site "www.pole-de-competences-verre.fr", s'il l'a autoris&eacute;, un cookie peut s'installer automatiquement sur son logiciel de navigation.<br />Le cookie est un bloc de donn&eacute;es qui ne permet pas d'identifier les utilisateurs mais sert &agrave; enregistrer des informations relatives &agrave; la navigation de celui-ci sur le site.<br />Le param&eacute;trage du logiciel de navigation permet d'informer de la pr&eacute;sence de cookies et &eacute;ventuellement de la refuser de la mani&egrave;re suivante :</p>
<ul>
<li>Pour Mozilla Firefox :&nbsp;<a href="https://support.mozilla.org/fr/kb/activer-desactiver-cookies">https://support.mozilla.org/fr/kb/activer-desactiver-cookies</a></li>
<li>Pour Google Chrome :&nbsp;<a href="https://support.google.com/chrome/answer/95647?hl=fr">https://support.google.com/chrome/answer/95647?hl=fr</a></li>
<li>Pour Internet Explorer :&nbsp;<a href="http://windows.microsoft.com/fr-fr/windows7/block-enable-or-allow-cookies">http://windows.microsoft.com/fr-fr/windows7/block-enable-or-allow-cookies</a></li>
<li>Pour Safari :&nbsp;<a href="http://support.apple.com/kb/PH17191?viewlocale=fr_FR">http://support.apple.com/kb/PH17191?viewlocale=fr_FR</a></li>
<li>Pour Op&eacute;ra :&nbsp;<a href="http://help.opera.com/Windows/10.20/fr/cookies.html">http://help.opera.com/Windows/10.20/fr/cookies.html</a></li>
<li>Pour tout autre navigateur, l'utilisateur devra consulter le manuel d'utilisation de son logiciel afin de trouver la m&eacute;thode de d&eacute;sactivation des cookies sur ce dernier.</li>
</ul>
<h4>Donn&eacute;es personnelles</h4>
<p>Le site "www.pole-de-competences-verre.fr" ne collecte pas de donn&eacute;es &agrave; caract&egrave;re personnel. Toutefois si le cas devait se pr&eacute;senter l&rsquo;utilisateur du site "www.pole-de-competences-verre.fr" est inform&eacute; que ses donn&eacute;es :</p>
<p>&nbsp;</p>
<ul>
<li>Seront collect&eacute;es de mani&egrave;re loyale et licite,</li>
<li>Seront collect&eacute;es pour des finalit&eacute;s d&eacute;termin&eacute;es, explicites et l&eacute;gitimes, ne seront pas trait&eacute;es ult&eacute;rieurement de mani&egrave;re incompatible avec ces finalit&eacute;s,</li>
<li>Ne seront pas destin&eacute;es &agrave; &ecirc;tre transmises &agrave; des tiers.</li>
<li>Seront ad&eacute;quates, pertinentes et non excessives au regard des finalit&eacute;s pour lesquelles elles sont collect&eacute;es et de leurs traitements ult&eacute;rieurs, sont exactes et compl&egrave;tes,</li>
<li>Seront conserv&eacute;es sous une forme permettant l&rsquo;identification des personnes concern&eacute;es pendant une dur&eacute;e qui n&rsquo;exc&egrave;de pas la dur&eacute;e n&eacute;cessaire aux finalit&eacute;s pour lesquelles elles seront collect&eacute;es et trait&eacute;es.</li>
<li>Toutes les pr&eacute;cautions sont prises pour pr&eacute;server la s&eacute;curit&eacute; des donn&eacute;es, et notamment pour &eacute;viter qu&rsquo;elles ne soient d&eacute;form&eacute;es, endommag&eacute;es ou que des tiers non autoris&eacute;s y aient acc&egrave;s.</li>
</ul>
<p>Conform&eacute;ment &agrave; la Loi n&deg;78-17 du 6 janvier 1978 relative &agrave; l&rsquo;Informatique, aux Fichiers et aux Libert&eacute;s, modifi&eacute;e par la Loi n&deg;2004-801 du 6 ao&ucirc;t 2004, l'utilisateur b&eacute;n&eacute;ficie d&rsquo;un droit d&rsquo;opposition (article 38), d&rsquo;acc&egrave;s (article 39) et de rectification (article 40) des informations qui le concernent. Si l'utilisateur souhaite exercer ce droit et obtenir communication des informations le concernant, il peut le demander&nbsp;au <a href="mailto:webmaster@cerfav.fr">Cerfav</a>.</p>
<p>L'utilisateur du site internet "www.pole-de-competences-verre.fr" est tenu de respecter la Loi n&deg;78-17 du 6 janvier 1978 relative &agrave; l&rsquo;Informatique, aux Fichiers et aux Libert&eacute;s, modifi&eacute;e par la Loi n&deg;2004-801 du 6 ao&ucirc;t 2004, dont la violation est passible de sanctions p&eacute;nales. Il doit notamment s'abstenir, s'agissant des informations &agrave; caract&egrave;re personnel auxquelles il acc&egrave;de ou pourrait acc&eacute;der, de toute collecte, de toute utilisation d&eacute;tourn&eacute;e d'une mani&egrave;re g&eacute;n&eacute;rale, de tout acte susceptible de porter atteinte &agrave; la vie priv&eacute;e ou &agrave; la r&eacute;putation des personnes.</p>
<h4>Liens hypertextes</h4>
<p>Les liens hypertexte pr&eacute;sents sur le site "www.pole-de-competences-verre.fr" et aiguillant les utilisateurs vers d&rsquo;autres sites internet n&rsquo;engagent en rien la responsabilit&eacute; de la r&eacute;daction quant au contenu de ces sites.<br />N&eacute;anmoins tout probl&egrave;me concernant des liens non disponibles ou faisant r&eacute;f&eacute;rence &agrave; des informations erron&eacute;es peut &ecirc;tre signal&eacute; au&nbsp;<a href="mailto:webmaster@cerfav.fr">Cerfav</a>.</p>
<h4>Proc&eacute;dure de notification, droit de r&eacute;ponse et droit de retrait</h4>
<p>L'utilisateur qui constaterait des inexactitudes, des informations erron&eacute;es ou des informations &agrave; caract&egrave;re manifestement illicite, est tenu d'en informer le&nbsp;<a href="mailto:webmaster@cerfav.fr">Cerfav</a>&nbsp;afin d'y&nbsp;mettre fin.<br />L'utilisateur b&eacute;n&eacute;ficie d'un droit de retrait et de modification des informations publi&eacute;es (textes, coordonn&eacute;es, images/photos, ...) &agrave; son &eacute;gard sur ce site. <br />Cet utilisateur est tenu d'en informer&nbsp;le&nbsp;<a href="mailto:webmaster@cerfav.fr">Cerfav</a>&nbsp;afin de supprimer les informations qui le concernerait.</p>
<h4>Propri&eacute;t&eacute; intellectuelle et Droits d&rsquo;auteur</h4>
<p>Le Cerfav&nbsp;est l'auteur, au sens des articles L. 111.1 et suivants du Code de la Propri&eacute;t&eacute; Intellectuelle, du site internet "www.pole-de-competences-verre.fr". Les photographies, textes, dessins, images anim&eacute;es ou non, s&eacute;quences sonores, documents t&eacute;l&eacute;chargeables (PDF, ...) disponibles sur ce site sont la propri&eacute;t&eacute; exclusive du Cerfav ou de tiers ayant&nbsp;autoris&eacute; le Cerfav &agrave; les utiliser.<br />Les reproductions, sur un support papier ou informatique, du site "www.pole-de-competences-verre.fr" et de son contenu sont autoris&eacute;es sous r&eacute;serve qu&rsquo;elles soient strictement r&eacute;serv&eacute;es &agrave; un usage personnel excluant tout usage &agrave; des fins publicitaires et/ou commerciales et/ou d&rsquo;information et/ou qu&rsquo;elles soient conformes aux dispositions de l&rsquo;article L. 122-5 du Code de la Propri&eacute;t&eacute; Intellectuelle.<br />A l&rsquo;exception des dispositions ci-dessus, toute reproduction, repr&eacute;sentation, utilisation ou modification, par quelque proc&eacute;d&eacute; que ce soit et sur quelque support que ce soit, de tout ou partie du site, de tout ou partie des diff&eacute;rentes contenus qui le composent, sans avoir obtenu l&rsquo;autorisation pr&eacute;alable de le Cerfav, est strictement interdite et constitue un d&eacute;lit de contrefa&ccedil;on sanctionn&eacute; par les articles L. 335-2 et suivants du Code de la Propri&eacute;t&eacute; Intellectuelle.</p>
<h4>Modification des mentions l&eacute;gales</h4>
<p>Le Cerfav se r&eacute;serve le droit de modifier la pr&eacute;sente notice &agrave; tout moment. L'utilisateur s'engage donc &agrave; la consulter r&eacute;guli&egrave;rement.</p>
<h4>Droit applicable</h4>
<p>Tout litige en relation avec l'utilisation du site "www.pole-de-competences-verre.fr" est soumis au droit fran&ccedil;ais. L'utilisateur reconna&icirc;t la comp&eacute;tence exclusive des tribunaux comp&eacute;tents de Nancy.</p></article>
</div>